git:
  paging:
    colorArg: always
    pager: delta -s --dark --paging=never
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 100
os:
  editPreset: 'claude-code'
  edit: 'claude-code --print "Generate a conventional commit message for these changes. Follow the format from CLAUDE.md. Be concise and use present tense." < {{filename}} > {{filename}}'
  editAtLine: 'claude-code --print "Generate a conventional commit message for these changes. Follow the format from CLAUDE.md. Be concise and use present tense." < {{filename}} > {{filename}}'
  editAtLineAndWait: 'claude-code --print "Generate a conventional commit message for these changes. Follow the format from CLAUDE.md. Be concise and use present tense." < {{filename}} > {{filename}}'
  editInTerminal: false
customCommands:
  - key: 'G'
    context: 'files'
    description: 'Generate AI commit message'
    command: 'git diff --cached > /tmp/staged_diff.txt && git log --oneline -10 --pretty=format:"%s" > /tmp/recent_commits.txt && echo -e "Recent commits for scope reference:\n$(cat /tmp/recent_commits.txt)\n\nStaged changes:\n$(cat /tmp/staged_diff.txt)" | claude --print "Generate a conventional commit message for these staged changes. Follow conventional commits format from CLAUDE.md. For multiple components affected: 1) If changes are closely related, use the primary scope 2) If major refactor/feature across multiple areas, consider broader scope or no scope 3) For truly separate changes, suggest splitting commits. Format: <type>[optional scope]: <description>. Add body with bullet points if needed for complex changes. Keep subject line under 50 chars when possible, present tense, lowercase, no period. Types: feat, fix, docs, style, refactor, perf, test, chore. Only output the commit message, nothing else." > /tmp/commit_msg.txt && git commit --edit -F /tmp/commit_msg.txt'
    loadingText: 'Generating commit message...'
    output: terminal
